version: "3.4"

services:
  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /proc/:/host/proc/:ro 
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro 
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      # - DD_LOG_LEVEL=debug
    ports:
      - 8126:8126

  django2-apache2:
    build:
      context: django_demo_app
      dockerfile: Dockerfile_wsgi
    ports:
      - '8020:80'
    environment:
      DATADOG_TRACE_AGENT_HOSTNAME: agent
      SOME_RANDOM_VALUE: hey_you
    volumes:
      - $PWD/django_demo_app:/var/www/html/app

  django14-apache2:
    build:
      context: django_14_app
      dockerfile: Dockerfile_wsgi
    ports:
      - '8014:80'
    environment:
      DATADOG_TRACE_AGENT_HOSTNAME: agent
      SOME_RANDOM_VALUE: hey_you
    volumes:
      - $PWD/django_14_app:/var/www/html/app